name: Integration Test Github
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: liskl/actions-docker-publish@main
      with:
        name: docker.pkg.github.com/liskl/actions-github-tag/actions-github-tag
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
